# Generated by Django 5.0.6 on 2024-06-28 20:36

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=60)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('dimensiones', models.CharField(max_length=60)),
                ('correo_propietario', models.CharField(max_length=60)),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen')),
                ('precio', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoArte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.arte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='arte',
            name='tipo_arte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoarte'),
        ),
    ]
