# Generated by Django 5.0.4 on 2024-05-10 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoArte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Arte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=60)),
                ('tecnica', models.CharField(max_length=60)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('dimensiones', models.CharField(max_length=60)),
                ('correo_propietario', models.CharField(max_length=60)),
                ('imagen', models.ImageField(default='default.jpg', upload_to='directorio/')),
                ('descripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoarte')),
            ],
        ),
    ]
