# Generated by Django 5.0.1 on 2024-05-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arte',
            old_name='descripcion',
            new_name='Tipo_Arte',
        ),
    ]
