# Generated by Django 5.0.4 on 2024-05-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_descripcion_arte_tipo_arte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arte',
            old_name='Tipo_Arte',
            new_name='tipo_arte',
        ),
    ]
