# Generated by Django 5.0.4 on 2024-05-13 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_tipo_arte_arte_tipo_arte'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='arte',
            table='arts',
        ),
    ]
