# Generated by Django 5.0.4 on 2024-05-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_arte_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='arte',
            table=None,
        ),
    ]
