# Generated by Django 5.0.1 on 2024-05-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_arte_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='descripcion',
            field=models.CharField(default='a', max_length=200),
        ),
    ]
