# Generated by Django 5.0.1 on 2024-05-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_arte_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
