# Generated by Django 5.0.1 on 2024-05-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_arte_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arte',
            name='tecnica',
        ),
    ]
