# Generated by Django 5.0.1 on 2024-05-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_arte_tecnica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='arte'),
        ),
    ]
