# Generated by Django 5.0.6 on 2024-05-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_arte_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='imagen',
            field=models.ImageField(null=True, upload_to='arte'),
        ),
    ]
