# Generated by Django 5.0.1 on 2024-05-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_arte_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arte',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='arte'),
        ),
    ]
