# Generated by Django 5.0.1 on 2024-05-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_arte_aprobado_alter_arte_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arte',
            name='aprobado',
        ),
    ]
