# Generated by Django 5.0.1 on 2024-05-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_arte_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='validacion',
            field=models.BooleanField(default=False),
        ),
    ]
