# Generated by Django 5.0.1 on 2024-05-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_arte_validacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arte',
            name='validacion',
        ),
    ]
