# Generated by Django 5.0.1 on 2024-05-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_arte_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='estado',
            field=models.CharField(choices=[('Aceptado', 'aceptado'), ('Rechazado', 'rechazado'), ('Pendiente', 'pendiente')], default='Pendiente', max_length=10),
        ),
    ]
