# Generated by Django 5.0.1 on 2024-05-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_arte_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='estado',
            field=models.CharField(choices=[('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10),
        ),
    ]
