# Generated by Django 5.0.6 on 2024-06-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_arte_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='precio',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
