# Generated by Django 5.0.4 on 2024-06-25 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_arte_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('arte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.arte')),
            ],
        ),
    ]
